### ISSUE TITLE
byte32 "what" in depend functions to Enum

### ISSUE THREAD

**Issue by charleenfei** [centrifuge/tinlake#102]
deviates from Maker pattern but potentially cleaner

**Comment by lucasvo** [comment]
I am not sure I'd agree on "potentially cleaner" - it definitely is not cheaper because the call args are byte32 anyway?

**Comment by charleenfei** [comment]
so i think it could be cheaper bc we would just pass in the index value in the enum as our call arg, which is uint8. also, could be a safety thing bc strings can be typo'd and cause a silent error/need to be changed in all functions if we use then in some case outside of the `depend`function (this might be overengineering tho). enums just wouldn't compile.

**Comment by manuelpolzhofer** [comment]
I think for now it is a bit hard to change it and not so many benefits. It would result in breaking changes for the JS lib. Let's keep it as it is for now.
