### ISSUE TITLE
refactor `pile.loans/pile.debtOf/pile.balanceOf`

### ISSUE THREAD

**Issue by charleenfei** [centrifuge/tinlake#117]
currently, these four methods have overlapping functionality. we should think about how to refactor/get rid of some of these to establish a clear design pattern, maybe just using `pile.loans`.

**Comment by ilinzweilin** [comment]
@charleenfei I think pile.burden has different functionality as it returns the debt including current accrued interest without actually updating the state. pile.debtOf(loan) returns the debt from the last state update and might not include the most recent interest...

**Comment by charleenfei** [comment]
@ilinzweilin, agreed, we can keep pile.burden out of this issue then
