### ISSUE TITLE
nft feed deployment and update script

### ISSUE THREAD

**Issue by manuelpolzhofer** [centrifuge/tinlake#347]
## ACs
- With the script the Admin can update multiple NFT parameters (interest rate & ceiling(max borrow amount)
  

## TCs:
- parse json file with nft entries and use seth to update the contract
- script takes json file as parameter

**Comment by denniswell** [comment]
ACs
- With the script the Admin can update multiple NFT parameters (interest rate & ceiling(max borrow amount)
  

## TCs:
-
