### ISSUE TITLE
Tinlake - replace the link to Slack with Discord in the help section

### ISSUE THREAD

**Issue by Tjure07** [centrifuge/tinlake#531]
Hello team,

on the centrifuge.tinlake.io homepage in the help section, the link to Slack can still be found.  

![image](https://user-images.githubusercontent.com/46523585/107645901-9f09e300-6c79-11eb-8d8b-c24304169f52.png)

Because of the migration from Slack to Discord please replace the link in the help section too. 

Thanks.
Christian

**Comment by manuelpolzhofer** [comment]
Thanks for info. It is already fixed in another Repo
